<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Recrutement Police RP — Formulaire</title>
  <style>
    :root{--bg:#0f172a;--card:#0b1220;--accent:#2563eb;--muted:#94a3b8;--glass:rgba(255,255,255,0.03)}
    *{box-sizing:border-box}
    body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,'Helvetica Neue',Arial;color:#e6eef8;background:linear-gradient(180deg,#071125 0%, #071a2a 60%);min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}
    .container{width:100%;max-width:980px;background:linear-gradient(180deg, rgba(255,255,255,0.02), rgba(255,255,255,0.01));border-radius:14px;padding:20px;box-shadow:0 10px 30px rgba(2,6,23,0.7);border:1px solid rgba(255,255,255,0.03);}
    header{display:flex;gap:16px;align-items:center;margin-bottom:12px}
    .logo{width:64px;height:64px;border-radius:10px;background:var(--glass);display:flex;align-items:center;justify-content:center;font-weight:700;color:var(--accent);font-size:20px}
    h1{margin:0;font-size:20px}
    p.lead{margin:4px 0 12px;color:var(--muted);font-size:14px}
    form{display:grid;grid-template-columns:1fr 320px;gap:18px}
    .card{background:linear-gradient(180deg, rgba(255,255,255,0.01), rgba(255,255,255,0.005));padding:14px;border-radius:10px;border:1px solid rgba(255,255,255,0.02)}
    .field{display:flex;flex-direction:column;margin-bottom:10px}
    label{font-size:13px;margin-bottom:6px;color:#cfe3ff}
    input[type="text"],input[type="email"],select,textarea,input[type="number"],input[type="date"],input[type="time"]{background:transparent;border:1px solid rgba(255,255,255,0.06);padding:10px;border-radius:8px;color:#eaf4ff}
    textarea{min-height:100px;resize:vertical}
    .small{font-size:12px;color:var(--muted)}
    .actions{display:flex;gap:8px;flex-wrap:wrap}
    button{background:var(--accent);color:white;border:none;padding:10px 12px;border-radius:8px;cursor:pointer}
    button.secondary{background:transparent;border:1px solid rgba(255,255,255,0.06)}
    .right-col{display:flex;flex-direction:column;gap:12px}
    .preview{background:linear-gradient(180deg, rgba(255,255,255,0.015), rgba(255,255,255,0.01));padding:12px;border-radius:8px}
    .entry{font-size:14px;color:#cfe3ff;margin-bottom:8px}
    .muted{color:var(--muted)}
    .img-preview{width:100%;height:160px;border-radius:8px;background:rgba(255,255,255,0.015);display:flex;align-items:center;justify-content:center;overflow:hidden}
    .img-preview img{max-width:100%;max-height:100%}
    footer{margin-top:12px;display:flex;justify-content:space-between;align-items:center}
    .notice{font-size:12px;color:var(--muted)}
    @media (max-width:880px){form{grid-template-columns:1fr;}.right-col{order:2}}
  </style>
</head>
<body>
  <div class="container" role="main">
    <header>
      <div class="logo">RP</div>
      <div>
        <h1>Formulaire — Recrutement Police (RP)</h1>
        <p class="lead">Remplis ce formulaire pour rejoindre la police sur notre serveur Roblox RP. Tes réponses seront envoyées à Discord et sauvegardées sur Google Sheets.</p>
      </div>
    </header>

    <form id="recruitForm" class="card" autocomplete="off">
      <div>
        <div class="field"><label for="robloxName">Pseudo Roblox</label><input id="robloxName" name="robloxName" type="text" required></div>
        <div class="field"><label for="age">Âge</label><input id="age" name="age" type="number"></div>
        <div class="field"><label for="discord">Tag Discord</label><input id="discord" name="discord" type="text"></div>
        <div class="field"><label for="experience">Expérience RP</label><select id="experience" name="experience"><option>Débutant</option><option>Intermédiaire</option><option>Avancé</option><option>Staff/Ancien membre</option></select></div>
        <div class="field"><label for="rank">Grade souhaité</label><select id="rank" name="rank"><option>Recrue</option><option>Agent</option><option>Sergent</option><option>Lieutenant</option><option>Capitaine</option></select></div>
        <div class="field"><label for="availability">Disponibilités</label><input id="availability" name="availability" type="text"></div>
        <div class="field"><label for="motivation">Motivation</label><textarea id="motivation" name="motivation"></textarea></div>
        <div class="field"><label for="history">Antécédents RP</label><textarea id="history" name="history"></textarea></div>
        <div class="field"><label for="screenshot">Capture d'écran</label><input id="screenshot" name="screenshot" type="file" accept="image/*"></div>
        <div class="field"><label for="webhook">Webhook Discord</label><input id="webhook" name="webhook" type="text" placeholder="https://discord.com/api/webhooks/..." /></div>
        <div class="actions"><button type="submit">Envoyer</button></div>
      </div>
      <aside class="right-col"><div class="card preview"><strong>Aperçu</strong><div id="previewArea">Remplis le formulaire puis envoie.</div></div><div class="card"><strong>Image</strong><div class="img-preview" id="imgPreview">Aucune image</div></div></aside>
    </form>

    <footer><div class="notice">Les données seront envoyées à Discord et sauvegardées dans Google Sheets.</div></footer>
  </div>

  <script>
    const GOOGLE_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbydqwQeyUbCqrSOi_aTLMDSgjYBDa04kzHekM5UmzBMS_2q7UWUIqc_GujZNMwbA2Iz/exec';
    const form = document.getElementById('recruitForm');
    const preview = document.getElementById('previewArea');
    const imgPreview = document.getElementById('imgPreview');

    form.addEventListener('submit', async (ev) => {
      ev.preventDefault();
      const data = Object.fromEntries(new FormData(form).entries());
      data.submittedAt = new Date().toISOString();

      // Preview
      preview.innerHTML = `<div><strong>${data.robloxName}</strong> (${data.age || '?'} ans)</div><div>${data.rank} - ${data.experience}</div><div>${data.discord}</div><div>${data.motivation}</div>`;

      // Send to Discord
      if(data.webhook && data.webhook.startsWith('http')) {
        try {
          await fetch(data.webhook, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:`**Nouvelle candidature RP Police**\n**Pseudo:** ${data.robloxName}\n**Grade:** ${data.rank}\n**Expérience:** ${data.experience}\n**Motivation:** ${data.motivation}`})});
        } catch(e){ console.error('Erreur Discord', e); }
      }

      // Send to Google Sheets
      try {
        await fetch(GOOGLE_SCRIPT_URL, {method:'POST', body: JSON.stringify(data)});
        alert('✅ Candidature envoyée et sauvegardée sur Google Sheets !');
      } catch(err){
        alert('⚠️ Erreur lors de l\'envoi vers Google Sheets : ' + err.message);
      }
    });
  </script>
</body>
</html>
